config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  get 'lobby', to: 'pages#lobby'
  get 'set_deck', to: 'pages#set_deck'
  get 'player_cards', to: 'pages#player_cards'
  get 'how_to_play', to: 'pages#how_to_play'
  resources :games, only: [:create, :show, :destroy, :update]
  resources :cards, only: [:create, :destroy, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_many :game_tokens
  has_many :cards

  def remove_from_lobby
    self.game_tokens.destroy_all
    SendTokenJob.perform_later(Array(GameToken.all))
  end

  def handle_player_2(current_user)
    if current_user != self.user && !self.player_2
      self.update_attribute(:player_2, current_user.username)
      self.remove_from_lobby()
    end
  end

  def handle_multiple_discards
    ids = self.card_id_list.split(%r{,\s*})
    self.cards.each do |card|
      card.update_attribute(:stage, 'out') if ids.include?(card.id.to_s)
    end
    self.update_attribute(:card_id_list, '')
  end

end

app/models/game_token.rb
class GameToken < ApplicationRecord
  belongs_to :game
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :games
  has_many :cards
  attr_accessor :login
  validates :username, uniqueness: true, presence: true, length: { minimum: 3 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.find_for_database_authentication warden_conditions
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.strip.downcase}]).first
  end

  def set_initial_card_state(cards, game)
    cards.shuffle.each.with_index do |card, i|
      card.update_attribute(:stage, "hand") if i < 5
      card.update_attribute(:stage, "deck") if i >= 5
      card.update_attribute(:game_id, game.id)
    end
  end

  def add_cards_to_game(cards, game)
    game.cards.concat(cards)
  end

  def prepare_cards(cards, game)
    self.set_initial_card_state(cards, game)
    self.add_cards_to_game(cards, game)
  end

  def handle_player_1_card_prep(cards, game)
    if self == game.user && !game.player_1_cards_prepped
      self.prepare_cards(cards, game)
      game.update_attribute(:player_1_cards_prepped, true) 
    end
  end

  def handle_player_2_card_prep(cards, game)
    if self != game.user && !game.player_2_cards_prepped
      self.prepare_cards(cards, game)
      game.update_attribute(:player_2_cards_prepped, true) 
    end
  end

  def handle_card_prep(cards, game)
    self.handle_player_1_card_prep(cards, game)
    self.handle_player_2_card_prep(cards, game)
  end

  def hand_card_count
    self.cards.count { |card| 
      card.stage == 'hand' 
    }
  end

  def draw_card
    self.cards.each do |card|
      if card.stage == 'deck'
        card.update_attribute(:stage, 'hand')
        break
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:login, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :password_confirmation, :current_password])
  end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  def create
    card = current_user.cards.create(card_params)
    card.update_attribute(:game_id, 0)
  end

  def destroy
    card = Card.find(params[:id])
    card.destroy
  end

  def update
    card = Card.find(params[:id])
    card.update_attributes(card_params)
    if current_user.hand_card_count < 5
      current_user.draw_card
    end
    card.game.update_attribute(:host_turn, !card.game.host_turn)
    SendGameAndCardsJob.perform_later(card.game)
  end

  private

  def card_params
    params.require(:card).permit(:face, :suit, :value, :stage, :place, :recipient_card_id)
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:destroy, :update]

  def create
    @game = current_user.games.create(player_1: current_user.username)
    @game.game_tokens.create(host_username: @game.user.username)
    SendTokenJob.perform_later(Array(GameToken.all))
    redirect_to game_path(@game)
  end

  def show
    @game = current_game
    current_user.handle_card_prep(current_user.cards, @game)
    @game.handle_player_2(current_user)
    SendGameAndCardsJob.perform_later(@game)
  end

  def destroy
    @game = current_game
    @game.update_attribute(:absent_player_id, current_user.id)
    SendGameJob.perform_later(@game)
    @game.remove_from_lobby()
    @game.destroy
  end

  def update
    game = current_game
    game.update_attributes(game_params)
    game.handle_multiple_discards
    if current_user.hand_card_count < 5
      current_user.draw_card
    end
    game.update_attribute(:host_turn, !game.host_turn)
    SendGameAndCardsJob.perform_later(game)
  end

  private

  def current_game
    @game ||= Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:card_id_list)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:lobby, :set_deck, :player_cards]

  def home
    @game = Game.new
  end

  def lobby
    if current_user.cards.count < 15
      redirect_to root_path
    end
    @game_tokens = GameToken.all
  end

  def set_deck
  end

  def player_cards
    render json: current_user.cards
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/games/show.html.erb
<div class="page-content green">

  <%= react_component("Game", {
    initialGame: @game,
    root_url: root_url,
    current_user: current_user,
    initialCards: @game.cards
  }) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Caravan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar fixed-top navbar-toggleable-md navbar-inverse bg-inverse header-color">
      <div class="green">
        <h4><%= link_to 'Go To Homepage', root_path, class: "green" %></h4>
        <% if current_user %>
          <h5><%= "Currently logged in as #{current_user.username}" %></h5>
        <% end %>
      </div>

      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="green">More Info</span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <h5 class="row green">
          <div class="column leftward-header-elements">
            <%= link_to "How to play", how_to_play_path, class: "green header-info" %>
            <div class="header-info">Email:</div>
            andystrube64@gmail.com
          </div>
          <div class="column">
            <%= link_to 'https://github.com/Learningstuff98/caravan' do %>
              <div class="fa fa-github-square header-info link green"> Github</div>
            <% end %>
            <br/>
            <%= link_to 'https://www.linkedin.com/in/andy-strube-6231ba152/' do %>
              <div class="fa fa-linkedin-square header-info link green"> Linkedin</div>
            <% end %>
            <br/>
            <%= link_to 'https://docs.google.com/document/d/1qm4nBdIZfsx8zh4IwYvkVuQYclpOXUCVxnC9vV3_eBM/edit' do %>
              <div class="fa fa-file-text link green"> Resume</div>
            <% end %>
          </div>
        </h5>
      </div>
    </nav>

    <br/><br/><br/><br/><br/>

    <h4 class="green text-center user-notice">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </h4>

    <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="text-center box top-margin col-8">
    <% if current_user %>
      <% if current_user.cards.count >= 15 %>
        <%= simple_form_for @game, url: games_path do |f| %>
          <h3><%= f.submit 'Host match', class: 'green host-match-btn' %></h3>
        <% end %>
        <br/>
        <h3><%= link_to "Go to lobby", lobby_path, class: "green" %></h3>
        <br/>
      <% else %>
        <h3 class="green">
          <div>You need to have at least 15 cards</div>
          <div>in your deck to play</div>
        </h3>
        <br/>
      <% end %>
      <h3><%= link_to "Set your deck", set_deck_path, class: "green" %></h3>
      <br/>
      <h3><%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "green" %></h3>
    <% else %>
      <h3><%= link_to "Log in", new_user_session_path, class: "green" %></h3>
      <br/>
      <h3><%= link_to "Sign up", new_user_registration_path, class: "green" %></h3>
    <% end %>
    <br/>
    <h3><%= link_to "How to play", how_to_play_path, class: "green" %></h3>
  </div>
</div>

app/views/pages/how_to_play.html.erb
<div class="page-content green col-9">
  <h3>
    Caravan is a card game from Fallout New Vegas
    that I've enjoyed so I decided to program it.

    <br/><br/>

    This is a two player game that can be thought of as being
    similar to blackjack, but times three as shown below.

    <br/><br/>
    <%= image_tag 'overview.png', class: 'game-image img-fluid' %>
    <br/><br/>

    There are six tracks total, three to each player. Each track
    has a number value that's derived from the cards on that track.

    <br/><br/>

    The goal is to get your tracks into bidding range, 21 to 26, in order
    to sell the track. The game is over when there are three sales total.
    Whoever has the majority of the sales wins.

    <br/><br/>

    Caravan is somewhat based on luck in that you'll be drawing cards from a deck,
    but it's largely based on deck composition and know how.
    Players will need to choose cards to add to their personal deck. The options
    are as follows:
    <br/><br/>
    Number cards 1 through 10 of all suits.
    <br/>
    Kings of all suits.
    <br/>
    Jacks of all suits.

    <br/><br/>

    There is a maximum of 3 of each of the above listed cards and a maximum
    of 50 cards total that one can have in their deck.
    Each player will need to have a minimum of 15 cards in their deck to play.

    <br/><br/>

    Each player will have a hand of 5 cards, unless they're running out of cards,
    in which case that player loses.

    <br/><br/><br/>

    Tracks can have the following states:
    <br/><br/>
    forSale: Having a value below 21.
    <br/><br/>
    Sold: Being in bidding range (21 to 26).
    <br/><br/>
    Tied: Being in bidding range (21 to 26), but being tied with your opponents track.
    <br/><br/>
    Outbid: Being in bidding range (21 to 26), but the opposing track is also in bidding range
    and of a higher value.
    <br/><br/>
    Bust: Over 26.

    <br/><br/><br/>

    Face Cards<br/><br/>
    Kings can be placed on any number card, including your opponent's.
    Kings inherit the number value that they're placed on and contribute to
    the track's value, shown below.
    <br/><br/>

    <%= image_tag 'placedking.png', class: "game-image img-fluid" %>

    <br/><br/>

    The king has been placed on top of the seven card, which makes the total 24.

    <br/><br/>

    Jacks remove the number card that they're placed on, along with any kings that are placed
    on that card. Jacks can be used on both your cards and your opponent's cards.

    <br/><br/>

    In the above example, a jack could be used to remove the seven card, which would also
    remove the king thats on top of it. Or it could be used to remove the ten card below it,
    or the seven card to the left.

    <br/><br/><br/>

    Direction<br/>
    All tracks have a direction, the default being flat. Direction will be going up if the
    last card's value is higher then the card before it. The direction will be going down
    if the last card's value is lower then the card before it.
    <br/><br/>
    Flat:<br/>
    If the tracks direction is flat, then any number card of any suit can be placed.
    <br/><br/>
    Down:<br/>
    If the tracks direction is going down, then the player will need a card that's of a lower
    value then the last card in said track, or a card of the same suit as the last card to
    place a card on the track.
    <br/><br/>
    Up:<br/>
    If the tracks direction is going up, then the player will need a card that's of a higher
    value then the last card in said track, or a card of the same suit as the last card to
    place a card on the track.

    <br/><br/><br/>

    Closing thoughts<br/>
    If you know how to play caravan, you may have noticed that I made a few minor changes.
    I did this for balance purposes. Think of the changes as house rules. Also, I made this
    app for learning purposes, not to make a PERFECT recreation of caravan.
  </h3>
</div>

<br/><br/><br/><br/><br/>

app/views/pages/lobby.html.erb
<div class="green page-content">
  <h1>Lobby</h1>

  <br/><br/>

  <%= react_component("Lobby", {
    game_tokens: @game_tokens,
    root_url: root_url
  }) %>

</div>

app/views/pages/set_deck.html.erb
<div class="center-set-deck green">

  <%= react_component("SetDeck", { root_url: root_url, cards: current_user.cards }) %>

</div>